### PR TITLE
Mavenize + fix some listener priorities

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by MrTigreroux** [comment]
Hello, thanks for the fix.
I don't really know how works maven and what it permits so I prefer don't use it for the moment.
Thanks for the "general cleanup" but the "() -> {" for runnables is more optimized or just more fast to write ?
Same ask for the StringBuilder, what's the difference between append() and += ?
Also, the check for class UserUtils was because sometimes I got an error saying the class wasn't found.

**Comment by sgdc3** [comment]
> Also, the check for class UserUtils was because sometimes I got an error saying the class wasn't found.

Probably it was caused by a compiler error

> I don't really know how works maven and what it permits so I prefer don't use it for the moment.

After the initial setup it is very easy to use, what ide are you using?

> Thanks for the "general cleanup" but the "() -> {" for runnables is more optimized or just more fast to write ?

https://softwareengineering.stackexchange.com/questions/195081/is-a-lambda-expression-something-more-than-an-anonymous-inner-class-with-a-singl

> Same ask for the StringBuilder, what's the difference between append() and += ?

String builders should be faster than '+'
https://stackoverflow.com/questions/35624421/java-string-vs-stringbuilder

**Comment by MrTigreroux** [comment]
I use Eclipse but if I use Maven, I would have to wait all the compilation at each modification or there isn't any link ?
I don't really understand what this format of documentation offer. TigerReports hasn't dependency, it compile fast and isn't Minecraft version dependent, updating is therefore easy to do.
I have a last question, is that really optimized to call toString() 4 times in place of storing it in a String ?
https://i.imgur.com/i9HSDzi.png
Thanks for the answers by the way.

**Comment by sgdc3** [comment]
>I use Eclipse but if I use Maven, I would have to wait all the compilation at each modification or there isn't any link ?

The error check works in realtime as a normal eclipse project.
The compilation of the jar just takes 8 seconds.

**Comment by sgdc3** [comment]
>I don't really understand what this format of documentation offer. TigerReports hasn't dependency, it compile fast and isn't Minecraft version dependent, updating is therefore easy to do.

It allows developers to impoert the project automatically, i personally dislike eclipse compiler, the missing classes is one of the problems that convinced me to use maven.

**Comment by sgdc3** [comment]
>I have a last question, is that really optimized to call toString() 4 times in place of storing it in a String ?
https://i.imgur.com/i9HSDzi.png

Whoops, i made that changes automatically, didn't notice that ;)

**Comment by sgdc3** [comment]
>I have a last question, is that really optimized to call toString() 4 times in place of storing it in a String ?
https://i.imgur.com/i9HSDzi.png

Yeah, the string builder just contains a char array, the toString method generates a string object on the way, it should be fater than creating a new string object on every '+' operation.

**Comment by sgdc3** [comment]
Now i have to do again everything :/

**Comment by MrTigreroux** [comment]
No, I made the most part of your fix.

**Comment by sgdc3** [comment]
The listener ones?

**Comment by MrTigreroux** [comment]
Why would the listeners be modified ?

**Comment by sgdc3** [comment]
@MrTigreroux You are listening at events with a low priority, plugins like skywarsx will cancel them in lobbies for example

**Comment by MrTigreroux** [comment]
They are marked as ignoring any cancellation.

**Comment by sgdc3** [comment]
ignoreCancelled means that the listener isn't triggered if the issue was cancelled by the previous listener. You need to set it to false, not true!

**Comment by MrTigreroux** [comment]
Ok I thought the opposite. Thanks for the info.

**Pull request closed without merging**
